// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/11/2568 16:15:58
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/CursorAI/ai-gateway/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/CursorAI/ai-gateway/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/CursorAI/ai-gateway/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/CursorAI/ai-gateway/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/CursorAI/ai-gateway/frontend/plugins/**/*.{js,ts,mjs}","D:/CursorAI/ai-gateway/frontend/composables/**/*.{js,ts,mjs}","D:/CursorAI/ai-gateway/frontend/utils/**/*.{js,ts,mjs}","D:/CursorAI/ai-gateway/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/CursorAI/ai-gateway/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/CursorAI/ai-gateway/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/CursorAI/ai-gateway/frontend/app.config.{js,ts,mjs}","D:/CursorAI/ai-gateway/frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;